services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: tarea_sqlserver_dev
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"  # Expuesto a tu máquina
    volumes:
      - sql_data_dev:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${SA_PASSWORD}" -C -Q "SELECT 1"
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  sql_data_dev:
